#version 450
#pragma shader_stage(compute)

#include "wavefront_common.glsl"

layout(set = 0, binding = 2) buffer AccumulatorBuffer
{
	vec4 accumulator[];
};

layout(set = 1, binding = 0) buffer RayBuffer
{
	uint counter;
	Ray rays[];
};

layout(set = 1, binding = 2) buffer MissRayBuffer
{
	uint counter;
	Ray rayIndices[];
} missRayStack;

layout(local_size_x = 16, local_size_y = 16) in;

void main()
{
	//
}
